[[gitignore]]
sources = ["base.ignore", "latex.ignore"]
target = ".gitignore"

[[latexmkrc]]
sources = ["base.pl", "lualatex.pl"]
target = "example/.latexmkrc"

[[license]]
sources = ["mit.txt"]
target = "license.txt"

[[makefile]]
sources = ["latex-package.mk"]
target = "makefile"
